"""Regenerate the progress table in README.md and the checklist in PROGRESS.md.

Solutions are discovered on disk rather than tracked by hand, so the numbers can
never drift out of sync with the code. A file counts as solved when its name
starts with the LeetCode problem id, e.g. ``0001_two_sum.py`` solves problem 1.

Usage:
    python scripts/update_progress.py            # rewrite the files in place
    python scripts/update_progress.py --check    # exit 1 if they are stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = Path(__file__).resolve().parent / "neetcode150.json"
NEETCODE_DIR = REPO_ROOT / "neetcode-150"
RANDOM_DIR = REPO_ROOT / "random-problems"
README = REPO_ROOT / "README.md"
PROGRESS = REPO_ROOT / "PROGRESS.md"

DIFFICULTIES = ("easy", "medium", "hard")
START_MARKER = "<!-- progress:start -->"
END_MARKER = "<!-- progress:end -->"
FILE_ID_PATTERN = re.compile(r"^(\d{1,4})[-_]")


@dataclass(frozen=True)
class Problem:
    id: int
    title: str
    slug: str

    @property
    def url(self) -> str:
        return f"https://leetcode.com/problems/{self.slug}/"


@dataclass(frozen=True)
class Category:
    dir: str
    name: str
    problems: tuple[Problem, ...]


def load_categories() -> list[Category]:
    raw = json.loads(DATA_FILE.read_text(encoding="utf-8"))
    return [
        Category(
            dir=entry["dir"],
            name=entry["name"],
            problems=tuple(
                Problem(id=p["id"], title=p["title"], slug=p["slug"]) for p in entry["problems"]
            ),
        )
        for entry in raw["categories"]
    ]


def solved_ids(directory: Path) -> set[int]:
    """Return the problem ids of every solution file directly inside a directory."""
    if not directory.is_dir():
        return set()
    ids: set[int] = set()
    for path in directory.glob("*.py"):
        match = FILE_ID_PATTERN.match(path.name)
        if match:
            ids.add(int(match.group(1)))
    return ids


def count_random_problems() -> dict[str, int]:
    return {level: len(solved_ids(RANDOM_DIR / level)) for level in DIFFICULTIES}


def build_readme_block(categories: list[Category], extras: dict[str, int]) -> str:
    """Build the summary table that lives between the progress markers in README.md."""
    lines = [
        "| Track | Solved | Total | Progress |",
        "| :---- | :----: | :---: | :------- |",
    ]

    total_solved = 0
    total_problems = 0
    for category in categories:
        found = solved_ids(NEETCODE_DIR / category.dir)
        solved = sum(1 for problem in category.problems if problem.id in found)
        total = len(category.problems)
        total_solved += solved
        total_problems += total
        lines.append(f"| {category.name} | {solved} | {total} | {progress_bar(solved, total)} |")

    lines.append(
        f"| **NeetCode 150 total** | **{total_solved}** | **{total_problems}** "
        f"| {progress_bar(total_solved, total_problems)} |"
    )

    extras_total = sum(extras.values())
    breakdown = " · ".join(f"{level}: {extras[level]}" for level in DIFFICULTIES)
    lines.append(f"| Supplemental LeetCode | {extras_total} | — | {breakdown} |")

    return "\n".join(lines)


def progress_bar(solved: int, total: int, width: int = 10) -> str:
    if total == 0:
        return "—"
    filled = round(width * solved / total)
    percent = round(100 * solved / total)
    return f"`{'█' * filled}{'░' * (width - filled)}` {percent}%"


def build_progress_file(categories: list[Category], extras: dict[str, int]) -> str:
    """Build the full PROGRESS.md checklist."""
    lines = [
        "# Progress",
        "",
        "Generated by `scripts/update_progress.py` — do not edit by hand.",
        "A box is checked when a matching solution file exists in the repository.",
        "",
    ]

    for category in categories:
        found = solved_ids(NEETCODE_DIR / category.dir)
        solved = sum(1 for problem in category.problems if problem.id in found)
        lines.append(f"## {category.name} ({solved}/{len(category.problems)})")
        lines.append("")
        for problem in category.problems:
            box = "x" if problem.id in found else " "
            lines.append(f"- [{box}] [{problem.id}. {problem.title}]({problem.url})")
        lines.append("")

    extras_total = sum(extras.values())
    lines.append(f"## Supplemental LeetCode ({extras_total})")
    lines.append("")
    for level in DIFFICULTIES:
        lines.append(f"- {level.capitalize()}: {extras[level]}")
    lines.append("")

    return "\n".join(lines)


def splice_readme(readme_text: str, block: str) -> str:
    start = readme_text.find(START_MARKER)
    end = readme_text.find(END_MARKER)
    if start == -1 or end == -1:
        raise SystemExit(
            f"README.md is missing the {START_MARKER} / {END_MARKER} markers; cannot update it."
        )
    head = readme_text[: start + len(START_MARKER)]
    tail = readme_text[end:]
    return f"{head}\n{block}\n{tail}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the generated files are out of date instead of writing them",
    )
    args = parser.parse_args()

    categories = load_categories()
    extras = count_random_problems()

    new_readme = splice_readme(
        README.read_text(encoding="utf-8"), build_readme_block(categories, extras)
    )
    new_progress = build_progress_file(categories, extras)

    old_progress = PROGRESS.read_text(encoding="utf-8") if PROGRESS.exists() else ""
    stale = new_readme != README.read_text(encoding="utf-8") or new_progress != old_progress

    if args.check:
        if stale:
            print("Progress files are out of date. Run: python scripts/update_progress.py")
            return 1
        print("Progress files are up to date.")
        return 0

    README.write_text(new_readme, encoding="utf-8")
    PROGRESS.write_text(new_progress, encoding="utf-8")
    print("Updated README.md and PROGRESS.md." if stale else "No changes needed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
